import { SidebarLink } from './sidebar-link.types';

/** Single source for sidebar navigation and navigation search. */
export const SIDEBAR_LINKS: readonly SidebarLink[] = [
  {
    id: 'dashboard',
    route: '/dashboard',
    label: 'Dashboard',
    icon: 'dashboard',
    visibility: 'authenticated',
    section: 'main',
    keywords: ['dashboard', 'home', 'overview'],
    aliases: ['overview'],
    priority: 10,
  },
  {
    id: 'markets',
    route: '/home',
    label: 'Markets',
    icon: 'home',
    visibility: 'always',
    section: 'main',
    keywords: ['markets', 'assets', 'symbols', 'prices'],
    aliases: ['browse'],
    priority: 10,
  },
  {
    id: 'portfolio',
    route: '/profile',
    label: 'Portfolio',
    icon: 'account_balance_wallet',
    visibility: 'authenticated',
    section: 'main',
    keywords: ['portfolio', 'holdings', 'balance', 'assets', 'profile'],
    aliases: ['wallet'],
    priority: 10,
  },
  {
    id: 'admin-users',
    label: 'Users',
    icon: 'group',
    visibility: 'admin',
    section: 'admin',
    keywords: ['users', 'admin'],
  },
  {
    id: 'admin-crypto',
    label: 'Crypto admin',
    icon: 'currency_bitcoin',
    visibility: 'admin',
    section: 'admin',
    keywords: ['crypto', 'admin', 'currencies'],
  },
  {
    id: 'admin-settings',
    label: 'Admin settings',
    icon: 'admin_panel_settings',
    visibility: 'admin',
    section: 'admin',
    keywords: ['settings', 'admin'],
  },
  {
    id: 'login',
    route: '/login',
    label: 'Login',
    icon: 'login',
    visibility: 'anonymous',
    section: 'footer',
    keywords: ['login', 'sign in'],
  },
  {
    id: 'register',
    route: '/register',
    label: 'Register',
    icon: 'person_add',
    visibility: 'anonymous',
    section: 'footer',
    keywords: ['register', 'sign up', 'create account'],
  },
];
