import { SidebarLink } from './sidebar-link.types';

/** Single source for sidebar navigation and navigation search. */
export const SIDEBAR_LINKS: readonly SidebarLink[] = [
  {
    id: 'dashboard',
    route: '/app/dashboard',
    label: 'Dashboard',
    icon: 'dashboard',
    visibility: 'authenticated',
    section: 'main',
    keywords: ['dashboard', 'home', 'overview'],
    aliases: ['overview'],
    priority: 10,
  },
  {
    id: 'markets',
    route: '/app/markets',
    label: 'Markets',
    icon: 'show_chart',
    visibility: 'always',
    section: 'main',
    keywords: ['markets', 'assets', 'symbols', 'prices'],
    aliases: ['browse'],
    priority: 10,
  },
  {
    id: 'portfolio',
    route: '/app/profile',
    label: 'Portfolio',
    icon: 'account_balance_wallet',
    visibility: 'authenticated',
    section: 'main',
    keywords: ['portfolio', 'holdings', 'balance', 'assets', 'profile'],
    aliases: ['wallet'],
    priority: 10,
  },
  {
    id: 'watchlist',
    label: 'Watchlist',
    icon: 'bookmark',
    visibility: 'authenticated',
    section: 'main',
    keywords: ['watchlist', 'favorites', 'bookmarks'],
    aliases: ['favorites'],
    priority: 8,
  },
  {
    id: 'admin-crypto',
    route: '/app/admin/crypto-currencies/new',
    label: 'Crypto admin',
    icon: 'currency_bitcoin',
    visibility: 'admin',
    section: 'admin',
    keywords: ['crypto', 'admin', 'currencies'],
  },
  {
    id: 'login',
    route: '/auth/login',
    label: 'Login',
    icon: 'login',
    visibility: 'anonymous',
    section: 'footer',
    keywords: ['login', 'sign in'],
  },
  {
    id: 'register',
    route: '/auth/register',
    label: 'Register',
    icon: 'person_add',
    visibility: 'anonymous',
    section: 'footer',
    keywords: ['register', 'sign up', 'create account'],
  },
];
